version: 1.0.{build}
clone_depth: 1
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake .. -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DERT_BUILD_CXX=OFF -DBUILD_PYTHON=OFF -DBUILD_APPLICATIONS=ON


    msbuild /m /p:Configuration=Release /p:Platform="x64" ERT.sln
